site_name: Mercado de Capitais do Brazil
repo_url: https://github.com/victor-vilela/capital-market-brazil
repo_name: victor-vilela/capital-market-brazil
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR

markdown_extensions: 
  - attr_list